FIELD_DEFS_BY_NOTICE = (

# ("Field name", "core schema", (5 flags for each notice schema, whether included), "type", dim, [const/enum values], default value, [bad values])
#     "type" is to be translated into python type and validator by the usint tesst program.
#     "dim" = None: The field is a scalar
#     "dim" = n: The field is an array with n items.
#     "enum" = [value1, value2, ...]: A list of valid enum values.
#     "default value" = None:  The field is required
#     "default value" = "NULL": The field is not required and the default value is null.
#     "default value" = any other value: The field is not required with the given default value.
#     "good values" = [good0, good1, ...]: A list of additional good (valid) values to test with. 
#     "bad values" = [bad0, bad1, ...]: A list of additional bad (invalid) values to test with.


("additional_info",   "AdditionalInfo",   (True,True,True,True,True),   ("str",   0,   [],   "",   [],   []),   ),
("alert_datetime",   "Alert",   (True,True,True,True,True),   ("str",   0,   [],   None,   [],   []),   ),
("alert_tense",   "Alert",   (True,True,True,True,True),   ("str",   0,   ["current","archival","planned","injection","commanded","test"],   None,   [],   []),   ),
("alert_type",   "Alert",   (True,True,True,True,True),   ("str",   0,   ["initial","update","retraction"],   None,   [],   []),   ),
("trigger_time",   "DateTime",   (True,True,True,True,True),   ("str",   0,   [],   None,   [],   []),   ),
("observation_start",   "DateTime",   None, "2025-01-02T03:45:12"),
("observation_stop",   "DateTime",   None, "2025-01-02T03:45:12"),
("observation_livetime",   "DateTime",   None, 1),
("luminosity_distance",   "Distance",   None, 2),
("luminosity_distance_error",   "Distance",   None, 0.1),
("t90",   "Duration",   None, 0.991),
("t90_error",   "Duration",   None, 0.02),
("t50",   "Duration",   None, 0.51),
("t50_error",   "Duration",   None, 0.1),
("event_name",   "Event",   (True,True,True,True,True),   ("str",   1,   [],   None,   [],   [[],["GRB245678A"]]),   ),
("id",   "Event",   (True,True,True,True,True),   ("str",   2,   [],   None,   [],   []),   ),
("data_archive_page",   "Event",   (True,True,True,True,True),   ("str",   0,   [],   None,   [],   []),   ),
("ref_type",   "Followup",   None, None),
("ref_instrument",   "Followup",   None, None),
("ref_ID",   "Followup",   None, None),
("reference",   "Followup",   None, None),
("latitude",   "GeoLocBase",   (True,True,True,False,False),   ("FLOAT_DEC",   0,   [],   None,   [],   []),   ),
("longitude",   "GeoLocBase",   (True,True,True,False,False),   ("FLOAT_RA",   0,   [],   None,   [],   []),   ),
("altitude",   "GeoLocBase",   None, None),
("mcilwain_l",   "GeoLocBase",   None, None),
("geoloc_time",   "GeoLocBase",   None, None),
("hardness_ratio",   "Hardness",   (False,True,False,False,False),   ("FLOAT_GZ",   0,   [],   None,   [],   []),   ),
("hardness_ratio_error",   "Hardness",   None, None),
("energy_range_soft",   "Hardness",   (False,True,False,False,False),   ("FLOAT_GZ",   2,   [[10.0,47.0]],   None,   [],   []),   ),
("energy_range_hard",   "Hardness",   (False,True,False,False,False),   ("FLOAT_GZ",   2,   [[47.0,291.0]],   None,   [],   []),   ),
("ra",   "Localization",   (False,True,True,True,True),   ("FLOAT_RA",   0,   [],   "null",   [],   []),   ),
("dec",   "Localization",   (False,True,True,True,True),   ("FLOAT_DEC",   0,   [],   "null",   [],   []),   ),
("ra_dec_error",   "Localization",   (False,True,True,True,True),   ("FLOAT_GZ",   0,   [],   "null",   [],   []),   ),
("containment_probability",   "Localization",   (False,True,True,True,True),   ("FLOAT_01",   0,   [],   "null",   [],   []),   ),
("systematic_included",   "Localization",   (False,True,True,True,True),   ("bool",   0,   [],   "null",   [],   []),   ),
("instrument_phi",   "Localization",   (False,True,True,False,False),   ("FLOAT_RA",   0,   [],   "null",   [],   []),   ),
("instrument_theta",   "Localization",   (False,True,True,False,False),   ("FLOAT_ZEN",   0,   [],   "null",   [],   []),   ),
("instrument_semimajor_angle",   "Localization",   None, None),
("healpix_url",   "Localization",   (False,False,True,True,True),   ("str",   0,   [],   "null",   [],   []),   ),
("healpix_file",   "Localization",   (False,False,True,True,True),   ("str",   0,   [],   "null",   [],   []),   ),
("pointing_ra",   "Pointing",   None, None),
("pointing_dec",   "Pointing",   None, None),
("roll",   "Pointing",   None, None),
("position_angle",   "Pointing",   None, None),
("attitude_quarternion",   "Pointing",   None, None),
("rotation",   "Pointing",   None, None),
("time",   "Pointing",   None, None),
("redshift",   "Redshift",   None, None),
("redshift_error",   "Redshift",   None, None),
("redshift_measure",   "Redshift",   None, None),
("redshift_type",   "Redshift",   None, None),
("mission",   "Reporter",   (True,True,True,True,True),   ("str",   0,   ["Fermi"],   None,   [],   []),   ),
("instrument",   "Reporter",   (True,True,True,True,True),   ("str",   0,   ["GBM"],   None,   [],   []),   ),
("record_number",   "Reporter",   (True,True,True,True,True),   ("INT_GZ",   0,   [],   None,   [],   []),   ),
("messenger",   "Reporter",   (True,True,True,True,True),   ("str",   0,   ["EM"],   "EM",   [],   ["GW","Neutrino"]),   ),
("spectrum",   "Reporter",   (True,True,True,True,True),   ("str",   0,   ["energy"],   "energy",   [],   ["wavelength","frequency"]),   ),
("units",   "Reporter",   (True,True,True,True,True),   ("str",   0,   ["keV"],   "keV",   [],   ["nm","Hz"]),   ),
("filter",   "Reporter",   None, None),
("far",   "Statistics",   None, None),
("trigger_type",   "Statistics",   (True,True,True,True,True),   ("str",   0,   ["rate"],   "rate",   [],   ["image"]),   ),
("net_count_rate",   "Statistics",   None, None),
("background_count_rate",   "Statistics",   None, None),
("rate_snr",   "Statistics",   (False,True,True,False,False),   ("FLOAT_GZ",   0,   [],   None,   [],   []),   ),
("rate_duration",   "Statistics",   (False,True,False,False,True),   ("FLOAT_GZ",   0,   [],   None,   [],   []),   ),
("rate_energy_range",   "Statistics",   (True,False,False,False,False),   ("FLOAT_GZ",   2,   [],   None,   [],   []),   ),
("image_snr",   "Statistics",   None, None),
("image_duration",   "Statistics",   None, None),
("image_energy_range",   "Statistics",   None, None),
("p_astro",   "Statistics",   None, None),
("classification",   "Statistics",   (False,True,False,False,False),   ("CLASSIFICATION",   0,   [],   None,   [],   []),   ),
("properties",   "Statistics",   None, None),
("best_fit_model",   "GammaRay",   None, None),
("spectral_energy_range",   "GammaRay",   None, None),
("hardness_ratio",   "GammaRay",   None, None),
("hardness_ratio_energy_range",   "GammaRay",   None, None),
("photon_flux",   "GammaRay",   (False,True,False,False,False),   ("FLOAT_GZ",   0,   [],   None,   [],   []),   ),
("photon_flux_error",   "GammaRay",   None, None),
("energy_flux",   "GammaRay",   None, None),
("energy_flux_error",   "GammaRay",   None, None),
("flux_energy_range",   "GammaRay",   None, None),
("flux_time_range",   "GammaRay",   None, None),
("fluence",   "GammaRay",   None, None),
("fluence_error",   "GammaRay",   None, None),
("fluence_energy_range",   "GammaRay",   None, None),
("fluence_time_range",   "GammaRay",   None, None),
("amplitude",   "PowerLaw",   None, None),
("amplitude_error",   "PowerLaw",   None, None),
("pivot_energy",   "PowerLaw",   None, None),
("alpha",   "PowerLaw",   None, None),
("alpha_error",   "PowerLaw",   None, None),
("amplitude",   "CutOffPowerLaw",   None, None),
("amplitude_error",   "CutOffPowerLaw",   None, None),
("pivot_energy",   "CutOffPowerLaw",   None, None),
("alpha",   "CutOffPowerLaw",   None, None),
("alpha_error",   "CutOffPowerLaw",   None, None),
("epeak",   "CutOffPowerLaw",   None, None),
("epeak_error",   "CutOffPowerLaw",   None, None),
("amplitude",   "Band",   None, None),
("amplitude_error",   "Band",   None, None),
("pivot_energy",   "Band",   None, None),
("alpha",   "Band",   None, None),
("alpha_error",   "Band",   None, None),
("epeak",   "Band",   None, None),
("epeak_error",   "Band",   None, None),
("beta",   "Band",   None, None),
("beta_error",   "Band",   None, None),
("NOTICE_TYPE",   0,   (True,True,True,True,True),   ("NOTICE_TYPE",   0,   ["FERMI_GBM_ALERT","FERMI_GBM_FLIGHT_POS","FERMI_GBM_GROUND_POS","FERMI_GBM_FINAL_POS","FERMI_GBM_SUBTHRESHOLD"],   None,   [],   []),   ),
("GROUND_GENERATED_NOTICE",   0,   (True,True,True,True,True),   ("bool",   0,   [],   0,   [],   []),   ),
("HITL",   0,   (True,True,True,True,True),   ("bool",   0,   [],   0,   [],   []),   ),
("TRIGGER_ALGORITHM_NUMBER",   0,   (True,False,False,False,False),   ("INT_GZ",   0,   [],   None,   [],   []),   ),
("DETECTORS_STATUS",   0,   (True,True,False,False,False),   ("str",   14,   ["triggered", "on", "off"],   None,   [],   []),   ),
("LOCALIZATION_ALGORITHM",   0,   (False,True,True,True,False),   ("str",   0,   [],   None,   [],   []),   ),
("LOCALIZATION_ENERGY_RANGE",   0,   (False,True,True,True,True),   ("FLOAT_GZ",   2,   [[44.0,281.0]],   None,   [],   []),   ),
("GALACTIC_L",   0,   (False,True,True,True,True),   ("FLOAT_RA",   0,   [],   "null",   [],   []),   ),
("GALACTIC_B",   0,   (False,True,True,True,True),   ("FLOAT_DEC",   0,   [],   "null",   [],   []),   ),
("SUN_DISTANCE",   0,   (False,True,True,True,True),   ("FLOAT_ZEN",   0,   [],   "null",   [],   []),   ),
("EARTH_ANGLE",   0,   (False,False,False,False,True),   ("FLOAT_ZEN",   0,   [],   None,   [],   []),   ),
("HARDNESS_CLASS",   0,   (False,False,False,False,True),   ("str",   0,   ["SOFT","HARD"],   None,   [],   []),   ),
("HEHI",   0,   (False,False,True,True,False),   ("bool",   0,   [False, True, "null"],   "null",   [],   []),   ),
("IN_LAT_FOV",   0,   (False,False,True,True,False),   ("bool",   0,   [False, True, "null"],   "null",   [],   []),   ),
("DURATION_CLASS",   0,   (False,False,True,True,True),   ("str",   0,   ["UNCERTAIN","SHORT","LONG", "null"],   "null",   [],   []),   ),
("RELIABILITY",   0,   (False,False,False,False,True),   ("str",   0,   ["LOW","MED","HIGH"],   None,   [],   []),   ),

)
